namespace SciFi.Players.Attacks {
    public class MorseCode {
        /// Uses the encoding specified by <c>GetLetter</c>.
        /// Generated by Util/morsecode.js and Wikipedia.
        static readonly byte[] letters = {
            // ABCDE
            0x42, 0x81, 0x85, 0x61, 0x20,
            // FGHIJ
            0x84, 0x63, 0x80, 0x40, 0x8E,
            // KLMNO
            0x65, 0x82, 0x43, 0x41, 0x67,
            // PQRST
            0x86, 0x8B, 0x62, 0x60, 0x21,
            // UVWXY
            0x64, 0x88, 0x66, 0x69, 0x8D,
            // Z
            0x83,
        };

        static readonly byte[] numbers = {
            // 01234
            0xBF, 0xBE, 0xBC, 0xB8, 0xB0,
            // 56789
            0xA0, 0xA1, 0xA3, 0xA7, 0xAF,
        };

        /// Translate a character to its morse code value, encoded using
        /// (number of pulses << 5) | (bit field of dash = 1, dot = 0).
        /// <param name="letter">A character in the set [A-Z0-9].</param>
        static byte GetLetter(char letter) {
            if (letter >= 'A' && letter <= 'Z') {
                return letters[letter - 'A'];
            } else if (letter >= '0' && letter <= '9') {
                return numbers[letter - '0'];
            } else {
                return 0;
            }
        }

        public static int Pulses(char letter) {
            return GetLetter(letter) >> 5;
        }

        /// If it's not a dash, it's a dot.
        /// Pulse is between 0 (inclusive) and Pulses(letter) (exclusive).
        public static bool IsDash(char letter, int pulse) {
            byte mask = (byte)(1 << (pulse));
            if ((GetLetter(letter) & mask) != 0) {
                return true;
            }
            return false;
        }
    }
}
