namespace SciFi.Players.Attacks {
    public class MorseCode {
        /// Letters in the form:
        /// (number of pulses << 5) | (bit field of dash = 1, dot = 0)
        /// Generated by Util/morsecode.js and Wikipedia.
        static readonly byte[] letters = {
            // ABCDE
            0x42, 0x81, 0x85, 0x61, 0x20,
            // FGHIJ
            0x84, 0x63, 0x80, 0x40, 0x8E,
            // KLMNO
            0x65, 0x82, 0x43, 0x41, 0x67,
            // PQRST
            0x86, 0x8B, 0x62, 0x60, 0x21,
            // UVWXY
            0x64, 0x88, 0x66, 0x69, 0x8D,
            // Z
            0x83,
        };

        static byte GetLetter(char letter) {
            if (letter >= 'A' && letter <= 'Z') {
                return letters[letter - 'A'];
            } else {
                return 0;
            }
        }

        public static int Pulses(char letter) {
            return GetLetter(letter) >> 5;
        }

        /// If it's not a dash, it's a dot.
        /// Pulse is between 0 (inclusive) and Pulses(letter) (exclusive).
        public static bool IsDash(char letter, int pulse) {
            byte mask = (byte)(1 << (pulse));
            if ((GetLetter(letter) & mask) != 0) {
                return true;
            }
            return false;
        }
    }
}
