using SciFi.Players.Attacks;

namespace SciFi.Environment.State {
    /// This represents the attack as an ability the player has.
    /// State information for objects generated by an attack, including
    /// non-projectiles, see `ObjectState`.
    public struct AttackState {
        public bool canCharge;
        public float chargeTime;
        public AttackType type;
        public AttackProperty properties;
        public short minDamage;
        public short maxDamage;
    }
}